version: "3.8"

networks:
    network:

volumes:
    mysql:
    node_modules:
    vendor:

services:

    core-integration-nginx:
        image: nginx:stable-alpine
        container_name: core-integration-nginx
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www/app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - core-integration-php
            - core-integration-mysql
        networks:
            - network

    core-integration-mysql:
        image: mysql:8.0
        container_name: core-integration-mysql
        restart: unless-stopped
        tty: true
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: coreintegrationdb
            MYSQL_ROOT_PASSWORD: secret
        command: "--log-bin-trust-function-creators=1"
        volumes:
            - mysql:/var/lib/mysql
        networks:
            - network
        cap_add:
            - SYS_NICE  # CAP_SYS_NICE

    core-integration-php:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        image: core-integration-php
        container_name: core-integration-php
        tty: true
        working_dir: /var/www/app
        volumes:
            - ./:/var/www/app
            - node_modules:/var/www/app/node_modules
            - vendor:/var/www/app/vendor
        command: /bin/sh -C "./entrypoint.sh"
        depends_on:
            - core-integration-mysql
        expose:
            - 9000
        networks:
            - network
